# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolabel',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='geolabel',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
